#!/bin/bash

# Quick Reference for sps3 Superset Development
# =============================================

echo "📚 sps3 Superset Development - Quick Reference"
echo "============================================="
echo ""
echo "🚀 Quick Commands:"
echo ""
echo "  Initial Setup (first time only):"
echo "    ./development/tools/setup-dev.sh"
echo ""
echo "  Start Development Server:"
echo "    ./development/tools/run-superset.sh"
echo ""
echo "  Manual Start:"
echo "    source .env.development"
echo "    superset run -p 8088 --with-threads --reload --debugger"
echo ""
echo "  Build Frontend:"
echo "    cd superset-frontend && npm run build"
echo ""
echo "  Watch Frontend (hot reload):"
echo "    cd superset-frontend && npm run dev"
echo ""
echo "📊 Database Info:"
echo "  Metadata DB: localhost:7432/superset"
echo "  Data Source: localhost:5432/airflow"
echo ""
echo "🌐 Access:"
echo "  URL: http://localhost:8088"
echo "  Users: admin, ScribeHubAppAdmin, ScribeHubApp"
echo ""
echo "🐛 Troubleshooting:"
echo "  Check Docker: docker ps | grep -E '7432|5432'"
echo "  Check Logs: See terminal output"
echo "  Clean Start: rm -rf venv && ./development/tools/setup-dev.sh"
echo ""
echo "📖 Full Documentation: DEVELOPMENT_README.md"
echo ""
