name: Docker_for_Scribe_Demo

on:
  workflow_dispatch:
    inputs:
      release:
        required: true
        description: The version to generate
      git-ref:
        required: true
        description: The git reference to checkout prior to running the docker build
      force-latest:
        required: true
        type: choice
        default: 'false'
        description: Whether to force a latest tag on the release
        options:
          - true
          - false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_preset: ["dev", "lean", "py310", "websocket", "dockerize"]
        platform: ["linux/amd64", "linux/arm64"]
        exclude:
          # disabling because slow! no python wheels for arm/py39 and
          # QEMU is slow!
          - build_preset: "dev"
            platform: "linux/arm64"
          - build_preset: "lean"
            platform: "linux/arm64"
      fail-fast: false
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        shell: bash
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          pip install click
          ./scripts/build_docker.py ${{ matrix.build_preset }} ${{ github.event_name }} --platform ${{ matrix.platform }}
